### ISSUE TITLE
opa_only flag values not honored

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/ais#109]
The API checks to see if there's a flag `opa_only` present in the query params. If it's there, it treats it at `opa_only=true`. However, this means that `opa_only=false` is handled the same way. Compare:

http://api.phila.gov/ais/v1/addresses/1807%20delancey%20st

http://api.phila.gov/ais/v1/addresses/1807%20delancey%20st?opa_only=False

**Comment by Alexander-M-Waldman** [comment]
Actually opa_only=false was being handled as the case where no opa flag is present; the issue here was it was cascading to an unmatched/parsed response instead of returning a 404.  This has been fixed so I am closing.
