### ISSUE TITLE
Unhandled Passyunk exceptions

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/ais#119]
Searching for `0 LISTER` on the `addresses` endpoint gives a 500 error:

http://api.phila.gov/ais/v1/addresses/0%20LISTER

**Comment by Alexander-M-Waldman** [comment]
What's happening is Passyunk is classifying it as an address but normalizing it to LISTER ST (w/o low_num) - either Passyunk can classify as a street and this will solve the issue, or AIS can handle addresses without low numbers as 404s. What do you think @rbrtmrtn ?

**Comment by rbrtmrtn** [comment]
@Alexander-M-Waldman I think it's OK to return a 404 for this.
