### ISSUE TITLE
Some PWD parcels missing

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/ais#131]
Browsing in Atlas, noticed a few PWD parcels were missing, e.g. `502975`. Does the data just need a refresh?

**Comment by Alexander-M-Waldman** [comment]
That is one of 375 parcel ids in the pwd_parcels ais engine table having a null address.

**Comment by rbrtmrtn** [comment]
Ah OK, I forgot about those. I'll close this out.
