### ISSUE TITLE
Concatenate intersection names in /search results

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/ais#132]
When you search for an intersection on the `/search` endpoint the results have `street_1` and `street_2` objects. It would be good to have a concatenated, fully-standardized intersection name as well. Perhaps `street_address` to be consistent with address results?

**Comment by Alexander-M-Waldman** [comment]
Closed by c44a3c81973e5b58cbd0631ea4e814f5f8962e32
