### ISSUE TITLE
Trailing slash breaks query

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/ais#14]
Works: https://api.phila.gov/ais/v1/addresses/1234%20market

Does not work: https://api.phila.gov/ais/v1/addresses/1234%20market/

Perhaps flask should ignore trailing slashes, or addresses should have invalid chars (like `/`, `$`, etc.) removed

**Comment by mjumbewu** [comment]
Resolved in commit 723f11205a8ac93864940a6fe4cb0a13cfb7a0f2
