### ISSUE TITLE
Cached (?) errors return 200 status code

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/ais#23]
If you search an `/addresses/randomzxoicuvk` it returns an HTTP status code of `404` the first time, but if you hit refresh it returns `200` every time after that. Could this be gatekeeper caching it? Hopefully it's just a flasky thing.

**Comment by mjumbewu** [comment]
Looks like this is on the gatekeeper end of things. GK returns a 200 for cached 404 responses.
