### ISSUE TITLE
11 NORTH 2ND STREET # 501 not found

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/ais#42]
`11 NORTH 2ND STREET # 501` matches to `11-15 N 2ND ST #501` in the OPA API but has no match in AIS.

**Comment by timwis** [comment]
caps lock bro

**Comment by rbrtmrtn** [comment]
lol. should be an api response ^^

**Comment by rbrtmrtn** [comment]
Will be fixed in #74.
