### ISSUE TITLE
Missing addresses in block search

### ISSUE THREAD

**Issue by mjumbewu** [CityOfPhiladelphia/ais#48]
Address `"505 W MOUNT AIRY AVE"` does not appear among the results for 500 block of W. Mt. Airy Ave. (nor does 501, 503, ..., 513, but 515 and above do, as do the even values on the block):
- Property result: https://api.phila.gov/ais/v1/addresses/505%20W%20MOUNT%20AIRY%20AVE?include_units&opa_only
- Block result: https://api.phila.gov/ais/v1/block/500%20W%20MOUNT%20AIRY%20AVE?include_units&opa_only

**Comment by rbrtmrtn** [comment]
[This line] is what's excluding child-of-range addresses from block results. `505 W MOUNT AIRY AVE` is an official OPA addresses (which DOR and PWD parcels agree on), but the PWD billing data has `505-13` which causes `505` to be treated as a child address. @Alexander-M-Waldman should we comment this line out for now, and Property will just return child addresses along with the parent?

**Comment by Alexander-M-Waldman** [comment]
Closed by c5071a46d48b369fdc55aa0fb096127f7906be9d
