### ISSUE TITLE
1930 Chestnut St, APT addresses not matching to Parcel

### ISSUE THREAD

**Issue by tswanson** [CityOfPhiladelphia/ais#6]
1930 CHESTNUT ST OFC
1930 CHESTNUT ST
1930-34 CHESTNUT ST

These addresses match pwd parcel 531391.

There are 108 APT addresses at this address that are true range matches - i.e. 1930 CHESTNUT ST APT 10B

**Comment by rbrtmrtn** [comment]
This could be resolved with #74.
