### ISSUE TITLE
ZIP for 1234 MARKET ST

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/ais#65]
is coming back as `19107-9997`. USPS has `19107-3727` ([see here](https://tools.usps.com/go/ZipLookupResultsAction!input.action?resultMode=1&companyName=&address1=1234+market+st&address2=&city=philadelphia&state=PA&urbanCode=&postalCode=&zip=)).

/cc @Alexander-M-Waldman @tswanson

**Comment by tswanson** [comment]
This is currently the intended behavior.  It is getting the zip4 for the building instead of the generic address
