### ISSUE TITLE
1935-37 Chestnut St, Confusing matching to the high and low numbers

### ISSUE THREAD

**Issue by tswanson** [CityOfPhiladelphia/ais#7]
These addresses are matched to PWD parcel 996352.
1935 CHESTNUT ST APT 2F
1935 CHESTNUT ST APT 2R
1935 CHESTNUT ST APT 3F
1935 CHESTNUT ST APT 3R
1935 CHESTNUT ST
1935-37 CHESTNUT ST

These addresses match to DOR Parcel 001S110288
1935 CHESTNUT ST
1935-37 CHESTNUT ST
1937 CHESTNUT ST - dor_parcel match

These addresses are true_range
1937 CHESTNUT ST # 1
1937 CHESTNUT ST APT 2F
1937 CHESTNUT ST APT 2R
1937 CHESTNUT ST APT 3F
1937 CHESTNUT ST APT 3R
1937 CHESTNUT ST APT 4F

**Comment by rbrtmrtn** [comment]
This will be resolved with #74.
