### ISSUE TITLE
opa_address is being normalized by passyunk

### ISSUE THREAD

**Issue by Alexander-M-Waldman** [CityOfPhiladelphia/ais#73]
Change update statement (ln. 341) to get opa_address from op.source_address instead of op.street_address

print('Populating OPA accounts...')
    prop_stmt = '''
		update address_summary asm
		set opa_account_num = op.account_num,
			opa_owners = op.owners,
			opa_address = op.**street_address**
		from address_property ap, opa_property op
		where asm.street_address = ap.street_address and
			ap.opa_account_num = op.account_num
	'''
    db.execute(prop_stmt)
    db.save()

**Comment by rbrtmrtn** [comment]
This seems to be resolved, closing.
