### ISSUE TITLE
Addresses on PORT ROYAL AVE erroring

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/ais#83]
Looks like all `PORT ROYAL AVE` addresses are being kicked out because of a parser error:

![image](https://cloud.githubusercontent.com/assets/1463553/21505280/ca484876-cc33-11e6-8859-c0aeed0c337b.png)

However the latest version of Passyunk doesn't raise any errors for these. @Alexander-M-Waldman was the latest engine data run with a different version of Passyunk?

**Comment by Alexander-M-Waldman** [comment]
@rbrtmrtn no, it was run with the current version. The error message comes from AIS load_streets: https://github.com/CityOfPhiladelphia/ais/blob/master/ais/engine/scripts/load_streets.py#L73

**Comment by rbrtmrtn** [comment]
@Alexander-M-Waldman but `load_streets` doesn't write to `address_error`, I don't think. There must have been something in `load_addresses` on the last run.

**Comment by Alexander-M-Waldman** [comment]
The error message was in the engine build log from the load_streets script so I looked there, but yes, the load_addresses script also handles passyunk parsing issues the same way

**Comment by Alexander-M-Waldman** [comment]
This has been in the log for the past 2 weeks, since Passyunk changes were incorporated

**Comment by rbrtmrtn** [comment]
Got it. We should probably try a few of those addresses in `DEV_MODE` and see what's going on. Not super urgent but it could be affecting other streets.

**Comment by rbrtmrtn** [comment]
See https://github.com/CityOfPhiladelphia/passyunk/issues/50
